### ISSUE TITLE
Documentation conversion meta-issue

### ISSUE THREAD

**Issue by jcheng5** [paws-r/paws#354]
Keeping track of all of the improvements I'd like to make to the documentation conversion process.

- [ ] Get rid of unnecessary/incorrect `\` escapes
- [ ] `<a>MethodName</a>` should be converted to internal links (e.g. the original docs for S3 ListObjectsV2); these currently are dropped with a warning
- [ ] Include documentation about responses
- [ ] Logic for detecting where the title ends can fail, see `?s3_restore_object`
- [ ] Split between "Description" and "Details" is arbitrary, put everything in "Description"
- [ ] "See also" sections should be pulled out into `\seealso{}`

**Comment by jcheng5** [comment]
These are all of the HTML tags that currently appear in the HTML docs.

* `<a>` - links to a function name in the same service, e.g. `<a>ListBuckets</a>`
* `<a href=>`
* `<a href= target=>`
* `<b>`
* `<br>`
* `<caution>` - used only once, in machinelearning-2014-12-12.normal.json
* `<code>`
* `<dd>`
* `<div>`
* `<div class=example>`
* `<div class=remarks>`
* `<div class=Remarks>`
* `<div class=seeAlso>`
* `<dl>`
* `<dt>`
* `<em>`
* `<filename>`
* `<fullname>`
* `<h4>`
* `<h5>`
* `<i>`
* `<important>` - block level
* `<li>`
* `<link linkend=>`
* `<literal>`
* `<note>`
* `<ol>`
* `<p>`
* `<p class=title>`
* `<pre>`
* `<replaceable>`
* `<strong>`
* `<title>` - used only in machinelearning-2014-12-12.normal.json as an intro to Note and Caution, e.g. `<note><title>Note</title> <p>This parameter blah blah blah<p></note>`
* `<u>`
* `<ul>`

**Comment by davidkretch** [comment]
Remaining HTML:
```
